# Generated by Django 5.1.1 on 2024-10-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionCategory',
            new_name='AuctionCategories',
        ),
    ]
