# Generated by Django 5.1.1 on 2024-10-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auctioncategory_auctioncategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionCategories',
            new_name='AuctionCategory',
        ),
        migrations.AlterModelOptions(
            name='auctioncategory',
            options={'verbose_name_plural': 'Auction Categories'},
        ),
    ]
