# Generated by Django 5.1.1 on 2024-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_listing_alter_bid_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='category_listings', to='auctions.listing'),
        ),
    ]
