# Generated by Django 5.1.1 on 2024-10-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_category_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listings',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(help_text='Select a category', related_name='categories', to='auctions.category'),
        ),
    ]
