# Generated by Django 5.1.1 on 2024-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(help_text='Select a category', related_name='categories', to='auctions.category'),
        ),
    ]
