# Generated by Django 5.1.1 on 2024-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_listing_category_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.ManyToManyField(related_name='bids', to='auctions.bid'),
        ),
    ]
