# Generated by Django 5.1.1 on 2024-10-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listing_current_bid_listing_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
