# Generated by Django 5.1.1 on 2024-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_bid_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
