# Generated by Django 5.1.1 on 2024-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_bid_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
