# Generated by Django 5.1.1 on 2024-10-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_bid_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_deleted',
        ),
    ]
